### ISSUE TITLE
Using image based textures

### ISSUE THREAD

**Issue by nhunzaker** [nulltask/node-three.js#2]
I was wondering if you had any solution for loading image textures, for example a substitute for:

``` javascript
var mapUrl    = "images/blah.png";
var map       = THREE.ImageUtils.loadTexture(mapUrl);
var material  = new THREE.MeshLambertMaterial({ map: map });
```

**Comment by nulltask** [comment]
thanks for your reporting. I fixed this issue on 0.1.0 and just published to npm registry :)

https://github.com/uniba/node-three.js/blob/master/examples/textures/index.js
![out](https://f.cloud.github.com/assets/291185/45679/b4662c9a-57b5-11e2-8bbf-8a3193b89db6.png)
